---

- name: "Create devops group"
  ansible.builtin.group:
    name: "devops"
    state: "present"
    gid: "1000"

- name: "Create devops user"
  ansible.builtin.user:
    create_home: true
    name: "devops"
    group: "devops"
    shell: "/bin/bash"
    uid: "1000"

- name: "Install .bashrc file"
  ansible.builtin.copy:
    src: ".bashrc"
    dest: "/home/devops/.bashrc"
    owner: "devops"
    group: "devops"
    mode: "0644"

- name: "Install .bash_profile file"
  ansible.builtin.copy:
    src: ".bash_profile"
    dest: "/home/devops/.bash_profile"
    owner: "devops"
    group: "devops"
    mode: "0644"

- name: "Configure user as sudoer"
  ansible.builtin.template:
    src: "sudoer.j2"
    dest: "/etc/sudoers.d/devops"
    owner: "root"
    group: "root"
    mode: "0440"

- name: "Modify locale configuration to set the chosen option"
  ansible.builtin.lineinfile:
    path: "/etc/locale.gen"
    regexp: "^# {{ locale_config }} UTF-8"
    line: "{{ locale_config }} UTF-8"

- name: "Reconfigure locale"
  ansible.builtin.command: dpkg-reconfigure --frontend=noninteractive locales
  changed_when: false

- name: "Update locale configuration"
  ansible.builtin.command: "update-locale LANG={{ locale_config }}"
  changed_when: false

- name: "Set locale wide system environment variables"
  ansible.builtin.template:
    src: "locale.j2"
    dest: "/etc/profile.d/100-set-locales.sh"
