---
# vars file for pulumi
base_arch:
  x86_64: 'x64'
  amd64: 'x64'
  aarch64: 'arm64'

# vars for pulumi
pulumi_pkg_url: "https://github.com/pulumi/pulumi/releases/download/{{ release.tag_name }}/pulumi-{{ release.tag_name }}-linux-{{ base_arch[ansible_architecture] }}.tar.gz"
pulumi_default_path: /usr/local/bin/
