# vars for uv
uv_pkg_url: "https://github.com/astral-sh/uv/releases/download/{{ uv_release.tag_name }}/uv-{{ ansible_architecture | lower }}-unknown-linux-gnu.tar.gz"
uv_default_path: "/home/devops/.local/bin/"
