# vars file for ansible
# base_arch:
#   x86_64: 'amd64'
#   amd64: 'amd64'
#   aarch64: 'arm64'

# vars for uv
# ansible_ppa_url: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/trusted.gpg.d/ansible.gpg] https://ppa.launchpadcontent.net/ansible/ansible-{{ version_to_install }}/ubuntu {{ ansible_distribution_release }} main"
uv_pkg_url: "https://github.com/astral-sh/uv/releases/download/{{ release.tag_name }}/uv-{{ ansible_architecture }}-unknown-linux-gnu.tar.gz"
uv_default_path: "/home/{{ build_user }}/.local/bin/"
