# https://taskfile.dev

version: '3'

vars:
  PACKER_FILE: packer/devops.pkr.hcl
  IMAGE_TAG:
    sh: git describe --tags --exact-match 2>/dev/null || echo "latest"

silent: true

tasks:
  build:
    desc: Build the docker image.
    cmds:
      - task: init
      - uv run packer build -var "image_tag={{.IMAGE_TAG}}" {{.PACKER_FILE}}

  build:debug:
    desc: Build the docker image but set packer in debug mode.
    cmds:
      - task: init
      - uv run packer build -on-error=ask -var "image_tag={{.IMAGE_TAG}}" {{.PACKER_FILE}}

  init:
    cmds:
      - uv run packer init {{.PACKER_FILE}}
