# https://taskfile.dev

version: '3'

vars:
  PACKER_FILE: packer/devops.pkr.hcl

silent: true

tasks:
  build:
    desc: Build the docker image.
    cmds:
      - task: init
      - uv run packer build {{.PACKER_FILE}}

  build:debug:
    desc: Build the docker image but set packer in debug mode.
    cmds:
      - task: init
      - uv run packer build -on-error=ask {{.PACKER_FILE}}

  init:
    cmds:
      - uv run packer init {{.PACKER_FILE}}
