---
# tasks file for install packer on Linux system

- name: "Find all versions of Packer"
  uri:
    url: https://releases.hashicorp.com/packer/index.json
    return_content: yes
  register: packer_index
  when: packer_version == "latest"

- name: "Finds the latest Packer version when latest var is define"
  set_fact:
    packer_version_to_install: "{{ (packer_index.content | from_json).versions | reject('search','-') | list | sort_versions | last }}"
  when: packer_version == 'latest'

- name: "Use the specified Packer version when latest var is not define"
  set_fact:
    packer_version_to_install: "{{ packer_version }}"
  when: packer_version != 'latest'

- name: "Install Packer"
  unarchive:
    src: "{{ packer_pkg_url }}"
    dest: "{{ packer_path }}"
    remote_src: yes
