---

- name: "Clean superfluos directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  loop:
    - "/var/lib/apt/lists"

- name: "Clean all temporary files"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  with_fileglob:
    - "/tmp/*"
