---

- name: "Clean apt lists cache"
  ansible.builtin.shell:
    cmd: "rm -rf /var/lib/apt/lists/* && mkdir -p /var/lib/apt/lists/partial"

- name: "Clean all temporary files"
  ansible.builtin.shell:
    cmd: "rm -rf /tmp/*"
