---
# file: roles/ansible/tasks/main.yml

- block:
    - name: "Create temporary directory"
      ansible.builtin.tempfile:
        state: "directory"
        prefix: "ansible-"
      register: temp_dir

    - name: "Download Ansible PPA key"
      ansible.builtin.get_url:
        url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x6125e2a8c77f2818fb7bd15b93c4a3fd7bb9c367"
        dest: "{{ temp_dir.path }}/ansible.asc"

    - name: "Convert key to binary GPG format"
      ansible.builtin.command:
        cmd: "gpg --dearmor {{ temp_dir.path }}/ansible.asc"
        creates: "{{ temp_dir.path }}/ansible.asc.gpg"

    - name: "Install PPA repository keychain file"
      ansible.builtin.copy:
        src: "{{ temp_dir.path }}/ansible.asc.gpg"
        dest: "/etc/apt/trusted.gpg.d/ansible.gpg"
        remote_src: true
        owner: "root"
        group: "root"
        mode: "0644"
        force: true

    - name: "Configure Ansible repository"
      ansible.builtin.apt_repository:
        repo: "{{ ansible_ppa_url }}"
        state: "present"

  always:
    - name: "Clean up temporary directory"
      ansible.builtin.file:
        path: "{{ temp_dir.path }}"
        state: "absent"
      when: temp_dir.path is defined

  when: not from_ubuntu_repo

- name: "Install Ansible"
  ansible.builtin.apt:
    name:
      - "ansible"
    state: "present"
    update_cache: true
  register: apt_ansible_install

- block:
    - name: "Create Ansible configuration file"
      ansible.builtin.shell:
        cmd: "ansible-config init --disabled -t all > /etc/ansible/ansible.cfg"
        creates: "/etc/ansible/ansible.cfg"
      changed_when: false

    - name: "Configure ansible-galaxy cache directory"
      community.general.ini_file:
        path: "/etc/ansible/ansible.cfg"
        section: "galaxy"
        option: "cache_dir"
        value: "/usr/share/ansible/collections/.ansible/galaxy_cache"
        state: "present"

    - name: "Ensure galaxy cache directory exists"
      ansible.builtin.file:
        path: "/usr/share/ansible/collections/.ansible/galaxy_cache"
        state: "directory"
        owner: "root"
        group: "root"
        mode: "0755"

    - name: "Install AWS collection for Ansible"
      ansible.builtin.command:
        cmd: "ansible-galaxy collection install amazon.aws:{{ aws_collection_version }} -p /usr/share/ansible/collections"
        creates: "/usr/share/ansible/collections/ansible_collections/amazon/aws"

  when: not from_ubuntu_repo
