---

- name: "Create temporary directory"
  ansible.builtin.tempfile:
    state: directory
    prefix: "taskfile-"
  register: temp_dir

- name: "Get latest version number of taskfile"
  ansible.builtin.uri:
    url: "https://api.github.com/repos/go-task/task/releases/latest"
    return_content: true
  register: taskfile_json

- name: "Set taskfile release fact"
  ansible.builtin.set_fact:
    taskfile_release: "{{ taskfile_json.content | from_json }}"

- block:
    - name: "Download latest version of taskfile"
      ansible.builtin.unarchive:
        src: "{{ taskfile_pkg_url }}"
        dest: "{{ temp_dir.path }}"
        remote_src: true

    - name: "Install taskfile"
      ansible.builtin.copy:
        src: "{{ temp_dir.path }}/task"
        dest: "{{ taskfile_default_path }}/task"
        owner: "root"
        group: "root"
        mode: "0755"
        remote_src: true

  always:
    - name: "Clean up temporary directory"
      ansible.builtin.file:
        path: "{{ temp_dir.path }}"
        state: "absent"
      when: temp_dir.path is defined
