---

- name: "Create temporary directory"
  ansible.builtin.tempfile:
    state: directory
    prefix: "joe-"
  register: temp_dir

- name: "Get latest version number of joe"
  ansible.builtin.uri:
    url: "https://api.github.com/repos/omata/joe/releases/latest"
    return_content: true
  register: joe_json

- name: "Set joe release fact"
  ansible.builtin.set_fact:
    joe_release: "{{ joe_json.content | from_json }}"

- block:
    - name: "Download latest version of joe"
      ansible.builtin.unarchive:
        src: "{{ joe_pkg_url }}"
        dest: "{{ temp_dir.path }}"
        remote_src: true

    - name: "Install joe"
      ansible.builtin.copy:
        src: "{{ temp_dir.path }}/build/linux-{{ base_arch[ansible_architecture | lower] }}/joe"
        dest: "{{ joe_default_path }}/joe"
        owner: "root"
        group: "root"
        mode: "0755"
        remote_src: true

  always:
    - name: "Clean up temporary directory"
      ansible.builtin.file:
        path: "{{ temp_dir.path }}"
        state: "absent"
      when: temp_dir.path is defined
