services:
  devops:
    image: devops:<version|latest>  # Set the version or use 'latest'
    container_name: devops
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
    volumes:
      - ${HOME}/.aws:/home/devops/.aws
      - ${PWD}/config.cnf:/home/devops/.ssh/config
      - ${HOME}/.ssh/hiberus/hda/:/home/devops/.ssh/<path tou your keys>:ro
      - ${HOME}/.ssh/apps:/home/devops/.ssh/apps:ro
      - ${PWD}/src:/home/devops/src  # Where src is the folder with IaC repositorie
      - ${PWD}/tmp:/home/devops/tmp
    env_file: my_env_vars.env
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
