version: '3.7'
services:
  devops:
    image: devops
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}/config.cnf:/home/${USER}/.ssh/config
      - ${HOME}/.ssh/hiberus/hda/:/home/${USER}/.ssh/hiberus/hda
      - ${HOME}/.ssh/apps:/home/${USER}/.ssh/apps
      - ${PWD}/src:/home/${USER}/src
      - ${PWD}/tmp:/home/${USER}/tmp
    env_file: my_env_vars.env
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
