---
# vars file for ansible-role-s5cmd
base_arch:
  i386: '32bit'
  x86_64: '64bit'
  amd64: '64bit'
  aarch64: 'ARM64'
  armv7l: 'ARM'

# vars for terraform in Linux system
croc_pkg_url: "https://github.com/schollz/croc/releases/download/{{ release.tag_name }}/croc_{{ release.tag_name[1:] }}_Linux-{{ base_arch[ansible_architecture] }}.tar.gz"
croc_default_path: /usr/local/bin/
