---

- name: "Create temporary directory"
  ansible.builtin.tempfile:
    state: directory
    prefix: "awscli-"
  register: temp_dir

- name: "Uninstall any version of 'awscli' installed by apt-get"
  ansible.builtin.apt:
    pkg:
      - "awscli"
    state: "absent"
    purge: true
    autoremove: true

- block:
    - name: "Download awscli-v2 installer"
      ansible.builtin.unarchive:
        src: "https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture | lower }}.zip"
        dest: "{{ temp_dir.path }}"
        remote_src: true
        creates: "{{ temp_dir.path }}/aws"
        mode: "0755"

    - name: "Install awscli-v2"
      ansible.builtin.command:
        cmd: "{{ temp_dir.path }}/aws/install"
        creates: "/usr/local/bin/aws"
      register: aws_install

    - name: "Show installer output"
      ansible.builtin.debug:
        var: aws_install
        verbosity: 2

  always:
    - name: "Clean up temporary directory"
      ansible.builtin.file:
        path: "{{ temp_dir.path }}"
        state: "absent"
      when: temp_dir.path is defined
