---
# vars file for taskfile
base_arch:
  i386: '386'
  x86_64: 'amd64'
  amd64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'arm'
  armv6l: 'arm'

# vars for taskfile
taskfile_pkg_url: "https://github.com/go-task/task/releases/download/{{ release.tag_name }}/task_linux_{{ base_arch[ansible_architecture] }}.tar.gz"
taskfile_default_path: /usr/local/bin/
