---
# vars file for terraform
base_arch:
  i386: '386'
  x86_64: 'amd64'
  amd64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'arm'
  armv6l: 'arm'

# vars for terraform in Linux system
terraform_pkg_url: "https://releases.hashicorp.com/terraform/{{ terraform_version_to_install }}/terraform_{{ terraform_version_to_install }}_{{ os_type }}_{{ base_arch[ansible_architecture] }}.zip"
terraform_default_path: /usr/local/bin/
os_type: linux
