---
# vars file for packer
base_arch:
  i386: '386'
  x86_64: 'amd64'
  amd64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'arm'
  armv6l: 'arm'

# vars for packer
packer_pkg_url: "https://releases.hashicorp.com/packer/{{ packer_version_to_install }}/packer_{{ packer_version_to_install }}_{{ os_type }}_{{ base_arch[ansible_architecture] }}.zip"
packer_default_path: /usr/local/bin/
os_type: linux
