---

- name: "Install required python packages from Ubuntu repositories"
  ansible.builtin.apt:
    name:
      - "python3-httpx"
      - "python3-jinja2"
      - "python3-pip"
      - "python3-pydantic"
      - "python3-pygit2"
      - "python3-pylint-common"
      - "python3-redis"
      - "python3-rich"
      - "python3-validators"
      - "python3-yaml"
      - "python3-yapf"
    state: present

- name: "Install latest boto3 and botocore via uv"
  ansible.builtin.command:
    cmd: "/home/devops/.local/bin/uv pip install --system boto3 botocore"
