---

- name: "Install required python packages from Ubuntu repositories"
  ansible.builtin.apt:
    name:
      - "python3-boto"
      - "python3-boto3"
      - "python3-botocore"
      - "python3-jinja2"
      - "python3-pip"
      - "python3-pydantic"
      - "python3-pygit2"
      - "python3-pylint-common"
      - "python3-redis"
      - "python3-rich"
      - "python3-validators"
      - "python3-yaml"
      - "python3-yapf"
    state: latest

# - block:
#   - name: "Update pip for main user"
#     pip:
#       name: pip
#       executable: "pip3"
#       extra_args: "--user"
#       state: "latest"

#   - name: "Install required python modules from pip"
#     pip:
#       name: "{{ pypy_modules }}"
#       executable: "pip3"
#       extra_args: "--user"
#       state: "latest"
#     when: pypy_modules
#   become: false
#   remote_user: "{{ build_user }}"
